# TCL File Generated by Component Editor 18.1
# Mon Feb 01 09:18:21 MSK 2021
# DO NOT MODIFY


# 
# splash_screen "Splash Screen" v1.0
#  2021.02.01.09:18:21
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module splash_screen
# 
set_module_property DESCRIPTION ""
set_module_property NAME splash_screen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "DSP/Video and Image Processing"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Splash Screen"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL splash_screen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file splash_screen.sv SYSTEM_VERILOG PATH splash_screen.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PIXELS_IN_PARALLEL INTEGER 4
set_parameter_property PIXELS_IN_PARALLEL DEFAULT_VALUE 4
set_parameter_property PIXELS_IN_PARALLEL DISPLAY_NAME "Pixels in parallel"
set_parameter_property PIXELS_IN_PARALLEL TYPE INTEGER
set_parameter_property PIXELS_IN_PARALLEL UNITS None
set_parameter_property PIXELS_IN_PARALLEL ALLOWED_RANGES {1 2 4}
set_parameter_property PIXELS_IN_PARALLEL HDL_PARAMETER true
add_parameter PIC_WIDTH INTEGER 400 ""
set_parameter_property PIC_WIDTH DEFAULT_VALUE 400
set_parameter_property PIC_WIDTH DISPLAY_NAME Ширина
set_parameter_property PIC_WIDTH WIDTH ""
set_parameter_property PIC_WIDTH TYPE INTEGER
set_parameter_property PIC_WIDTH UNITS None
set_parameter_property PIC_WIDTH ALLOWED_RANGES 0:2000
set_parameter_property PIC_WIDTH DESCRIPTION ""
set_parameter_property PIC_WIDTH HDL_PARAMETER true
add_parameter PIC_HEIGHT INTEGER 160 ""
set_parameter_property PIC_HEIGHT DEFAULT_VALUE 160
set_parameter_property PIC_HEIGHT DISPLAY_NAME Высота
set_parameter_property PIC_HEIGHT WIDTH ""
set_parameter_property PIC_HEIGHT TYPE INTEGER
set_parameter_property PIC_HEIGHT UNITS None
set_parameter_property PIC_HEIGHT ALLOWED_RANGES 0:2000
set_parameter_property PIC_HEIGHT DESCRIPTION ""
set_parameter_property PIC_HEIGHT HDL_PARAMETER true
add_parameter PIC_MIF STRING ../splashscreen.mif
set_parameter_property PIC_MIF DEFAULT_VALUE ../splashscreen.mif
set_parameter_property PIC_MIF DISPLAY_NAME Картинка
set_parameter_property PIC_MIF TYPE STRING
set_parameter_property PIC_MIF UNITS None
set_parameter_property PIC_MIF DISPLAY_HINT file:mif
set_parameter_property PIC_MIF HDL_PARAMETER true
add_parameter EMPTY_WIDTH INTEGER 4
set_parameter_property EMPTY_WIDTH TYPE INTEGER
set_parameter_property EMPTY_WIDTH VISIBLE false
set_parameter_property EMPTY_WIDTH HDL_PARAMETER true
set_parameter_property EMPTY_WIDTH DERIVED true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 1
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout aso_startofpacket startofpacket Output 1
add_interface_port dout aso_endofpacket endofpacket Output 1
add_interface_port dout aso_valid valid Output 1
add_interface_port dout aso_data data Output 24*PIXELS_IN_PARALLEL
add_interface_port dout aso_ready ready Input 1
add_interface_port dout aso_empty empty Output EMPTY_WIDTH

proc elaborate {} {
  set PIP [get_parameter_value PIXELS_IN_PARALLEL]
  switch -exact -- $PIP {
    1 { 
        set_port_property aso_empty termination true
        set_port_property aso_empty termination_value 0 
      }
    2 { 
        set_port_property aso_empty termination false
        set_parameter_value EMPTY_WIDTH 3 
      }
    4 { 
        set_port_property aso_empty termination false
        set_parameter_value EMPTY_WIDTH 4 
      }
  }
}